### ISSUE TITLE
Error when adding decorator to class

### ISSUE THREAD

**Issue by nrfribeiro** [aigoncharov/class-logger#12]
Hi,
I'am having a error when executing my code after adding the decorator to a class.

!  TypeError: Reflect.defineMetadata is not a function
    at D:\Wiredkode\Projects\Covid19NeuroTracking\Functions\functions\node_modules\class-logger\dist\src\log-class.decorator.js:7:13
    at __decorate (D:\Wiredkode\Projects\Covid19NeuroTracking\Functions\functions\lib\controlers\UsersController.js:5:95)
    at Object.<anonymous> (D:\Wiredkode\Projects\Covid19NeuroTracking\Functions\functions\lib\controlers\UsersController.js:20:5)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (D:\Wiredkode\Projects\Covid19NeuroTracking\Functions\functions\lib\express\endpoints\post_sysadmins.js:5:27)
!  We were unable to load your functions code. (see above)
   - It appears your code is written in Typescript, which must be compiled before emulation.
   - You may be able to run "npm run build" in your functions directory to resolve this.

**Comment by aigoncharov** [comment]
@nrfribeiro have installed `reflect-metadata`? See p.1 of the [installation guide](https://github.com/aigoncharov/class-logger#installation)

**Comment by nrfribeiro** [comment]
Hi,
It was my mistake. Is working :) thanks.

Now I have another question. 
Following the thread https://github.com/aigoncharov/class-logger/issues/1 is there any way to enable logging at runtime, meaning depending on the log level that I have configured on Winston, I want to fully disable class-logger. I have an envvar that I use to change Winston log level, and based on that I want to decide to fully activate on not class.logger.

**Comment by aigoncharov** [comment]
@nrfribeiro I left in that thread [a comment with the example](https://github.com/aigoncharov/class-logger/issues/1#issuecomment-481798515). Would it work for you?

**Comment by nrfribeiro** [comment]
Hi, I don't think so. 
I want to enable or to disable the log at runtime. The example you provided only works at the first time the class is instantiated/accessed. Unfortunately, I have a few singleton classes, and I would like to enable or disable the log at runtime

**Comment by aigoncharov** [comment]
@nrfribeiro the same principle applies
```ts
import { LogClass as LogClassOriginal, IClassLoggerConfig } from 'class-logger'

let enabled: boolean = true
export const enable = () => { enabled = true }
export const disable = () => { enabled = false }


export const LogClass = (config: IClassLoggerConfig) => {
  if (!enabled) {
    return () => undefined // return an empty decorator placeholder
  }
  return LogClassOriginal(config)
} 
```

**Comment by nrfribeiro** [comment]
Hi, Thanks for the reply.

**Comment by aigoncharov** [comment]
@nrfribeiro got it. In this case, it's not possible to completely disable the proxy creation, but you can make it not log anything,
See the [global config section](https://github.com/aigoncharov/class-logger#global-config) of the manual.
Whenever you want to disable the logging override `log` and `logError`
```
import { setConfig } from 'class-logger'

setConfig({
  log: () => {},
  logError: () => {}
})
```

This way you'll still have a wrapping proxy and you'll pay a performance penalty for that. However, I expect 99% of the apps not even noticing the performance impact.
